# Generated by Django 5.1.6 on 2025-02-24 05:06

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='dark_mode_enabled',
            field=models.BooleanField(default=False, help_text="User's preference for dark mode"),
        ),
        migrations.AddField(
            model_name='customuser',
            name='is_profile_complete',
            field=models.BooleanField(default=False, help_text='Whether the user has completed their profile'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='medical_conditions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('none', 'No Major Health Issues'), ('diabetes', 'Diabetes'), ('heart_disease', 'Heart Disease'), ('asthma', 'Asthma'), ('cancer', 'Cancer'), ('hypertension', 'Hypertension'), ('other', 'Other')], max_length=50), blank=True, help_text="List of user's medical conditions", null=True, size=None),
        ),
        migrations.AddField(
            model_name='customuser',
            name='preferred_hospital_network',
            field=models.CharField(blank=True, help_text='Preferred hospital network', max_length=100),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='copay',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Copay amount in dollars', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='features',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, help_text='List of plan features', null=True, size=None),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='max_coverage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum coverage amount in dollars', max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='network_hospitals',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, help_text='List of network hospitals', null=True, size=None),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='plan_type',
            field=models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('family', 'Family'), ('senior', 'Senior'), ('specialized', 'Specialized')], default='basic', help_text='Type of insurance plan', max_length=20),
        ),
        migrations.AddField(
            model_name='insuranceplan',
            name='popularity_score',
            field=models.FloatField(default=0.0, help_text='Plan popularity score based on user feedback and selections', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='PlanComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison_name', models.CharField(blank=True, help_text='Optional name for this comparison', max_length=255)),
                ('notes', models.TextField(blank=True, help_text='User notes about the comparison')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plans', models.ManyToManyField(help_text='Plans being compared', related_name='comparisons', to='insurance.insuranceplan')),
                ('user', models.ForeignKey(help_text='User who created the comparison', on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan Comparison',
                'verbose_name_plural': 'Plan Comparisons',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserDashboardPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_view', models.CharField(choices=[('list', 'List View'), ('grid', 'Grid View'), ('compact', 'Compact View')], default='grid', help_text="User's preferred view type", max_length=20)),
                ('show_premium_first', models.BooleanField(default=False, help_text='Whether to prioritize premium plans in display')),
                ('notification_preferences', models.JSONField(default=dict, help_text='JSON object containing notification preferences')),
                ('widgets_order', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), default=list, help_text='Order of dashboard widgets', size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='User whose preferences these are', on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dashboard Preference',
                'verbose_name_plural': 'Dashboard Preferences',
            },
        ),
    ]
