# Generated by Django 5.1.6 on 2025-02-24 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insurance', '0002_customuser_dark_mode_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='feedback_type',
            field=models.CharField(choices=[('recommendation', 'Recommendation'), ('plan', 'Insurance Plan'), ('ui', 'User Interface'), ('general', 'General')], default='general', help_text='Type of feedback', max_length=20),
        ),
        migrations.AddField(
            model_name='feedback',
            name='insurance_plan',
            field=models.ForeignKey(blank=True, help_text='Insurance plan this feedback is about', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedback', to='insurance.insuranceplan'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='ui_element',
            field=models.CharField(blank=True, help_text='UI element this feedback is about', max_length=100),
        ),
    ]
